[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SuperNu"
authors = [{name = "D Fernando", email = "ff1705@rit.edu"}]
dynamic = ["version", "description"]
